### ISSUE TITLE
т6 мех, его название

### ISSUE THREAD

**Issue by floppa-coder** [Sputnuc/Asterion#1]
Хищник → Глава, не понял чем они связаны. Поменяйте название. Ещё глава не правильно переведена в коде.

**Comment by Sputnuc** [comment]
Эм так то это не глава а монарх просто в файле глава

**Comment by floppa-coder** [comment]
> Эм так то это не глава а монарх просто в файле глава

... А, нууу, эмммм, ну где связь между хищником и монархом?

**Comment by AnDashikKozlov** [comment]
Да нигде особо, просто монарх звучит классно и всё.  Лол
